name = "MaGe"
uuid = "c72a0c40-e991-40c1-bf51-d364a8cc9db3"
authors = ["Paul Nemec"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SolidStateDetectors = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
