name = "MaGeSigGen"
uuid = "c72a0c40-e991-40c1-bf51-d364a8cc9db3"
authors = ["Paul Nemec"]
version = "0.1.3"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MJDSigGen = "d3f1610b-2cc8-4877-9c4b-1cc92a82e4fd"
MaGe = "a1237f97-e57a-43a8-8ead-9081d93d2731"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
