name = "MaGeAnalysis"
uuid = "c72a0c40-e991-40c1-bf51-d364a8cc9db3"
authors = ["Paul Nemec"]
version = "0.1.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
